### ISSUE TITLE
Final Effort, Keep Open: Submission plan for last week before deadline

### ISSUE THREAD

**Issue by ashishrana160796** [softgitron/LeviRank#3]
We should be planning for five system submissions before the deadline of May 2 approaches us. Tentative plan dates and submission system module details, let's decide it during the connect session today.

**Comment by PujitGolchha** [comment]
### Sunday Night or Monday Morning/Afternoon Submission:

**levirank_baseline**

```
* bm25: original query -> "nouns+verbs+adjective" [Preprocess the original to this form, lower case only] -> 1375 documents or hit list
  - Index Building, BM25: DocT5Query Expanded Corpus -> [Regular document preprocessing, like removing <query> ... </query>, removing stopwords, lower case] -> b, k {ideal values}.
  {Output: 1.5K documents from initial retrieval, hit list.}

* MonoT5: 1375 document input -> 1K document, [original documents, original query, removed query tags], time monitoring
* DuoT5: top-30 reranked with MonoT5 and 970 other documents appended.
* Stance: [original documents, original query] as inputs 
  - Two prediction models: Take models trained by Andrea, refering prediction scripts from QMUL to make it work.
 ```

**Comment by PujitGolchha** [comment]
Hello @ahmed-elzamarany 

We were trying to make dense retrieval work for both dense encoders and sparse encoders. But, it hasn't worked for us now. Please, can you try implementing that solution with `pyserini` library. Also, sharing the notebook link with you here.

* Notebook Link: https://drive.google.com/file/d/1acAkKqXe7ZznmYA0U7LrRdxOELj7BwLi/view?usp=sharing

**Comment by ashishrana160796** [comment]
### Final Submission Email Details

```
Till Sunday night, 1 May, 11:59 PM

Submission files 'qrel' extension, github repository link, docker container link, our baseline method should be running on TIRA and 'qrel' result file should also be there. {today running itself, during mail time, mention that it is running}. Also, as bottom-line we are expected to give docker code of one approach, I guess we are good if its currently running baseline solution itself only.

Approach Introduction & Methodology: 3 lines, & 1 line description for each submission.
```

---

### Submission Details: 5 Approaches for Submission

We plan to submit 5 submissions till May 1. First two will be prepared by @softgitron & @ahmed-elzamarany and the remaining three implementations by remaining 3 people. Also groups of {2,3}, both groups will review other groups code as well. The last three systems will also not be made available till the deadline they will only continue to exist in notebook form until then, no issues.

* __1. New baseline submission:__ BM25 + out-of-the-box implementations for mono-duo architecture. _(currently running on TIRA, let's keep that submission only as reference.)_

**For new submission, let's keep everything same as before baseline solution. But, @softgitron now on your personal setup make sure to re-rank first 50 documents with duoT5, if you can a bit higher by May 1. It'll be awesome as well!**

_Note: Aim of this baseline submission is to develop more accurate baseline reranker that the one running on TIRA as reference._


* __2. Dense retrieval submission:__ _(Colbert Dense Retrieval vs Contrastive Learning Retrieval)_. Please, see which one performs better retrieval, let's use average recall over 1.5k document retrieval as selection metric + Submission 1's baseline solution as the rest of the pipeline. Dear @ahmed-elzamarany  & @softgitron, this is a time consuming effort, please do discuss b/w yourself to align your efforts for these two submissions.  _{In progress, task by @ahmed-elzamarany : Hybrid retrieval vs Regular retrieval vs Constrastive learning based retrieval? @softgitron, do compare your metrics with @ahmed-elzamarany's resut.}_

_Note: If you guys have some other suggestion for measuring dense retrieval's performance. Please, feel free to share it! cool, all the best!_

---

Assigned work to @ashishrana160796, @PujitGolchha & @AndreeaCoaja 

* __3. Query expansion submission:__ Voting based query expansion + baseline from step 1 _(Separate submission, DuoT5 top-30 renrank, colab limit, if  more possible then more will be added)_

* __4. Pseudo relevance submission:__ Pseudo relevance bm25 _(ideal k, still in progress)_ + baseline from step 1 _(Separate submission, DuoT5 top-30 renrank, colab limit, if  more possible then more will be added)_

* __5. Voting + Pseudo relevance submission:__ Voting based query expansion + Pseudo relevance pooled query added + baseline from step 1 _(Separate submission, DuoT5 top-30 renrank, colab limit, if  more possible then more will be added)_

#### Task Assignment details for Group 2

A `submission_notebooks/` should be made where the plan is to keep only the notebooks that will help us in running the final run for the 3 systems below. 

* Implementation design will have a stored `csv` file after each step execution and the data will be committed in `submission_notebooks/data` directory on respective implementor's branch.
* Me & @PujitGolchha, we will be working on the complete execution of the pipeline till final qrel file generation part + we will coordinate amongst ourself for that.
* @AndreeaCoaja, we expect that you design the file `qrel` file generation + stance prediction script in one single notebook. Do refer, @softgitron's implementation for the same as reference.
  * We will will be giving a csv with `{qid, docid, query, doc_content, score}` as input and we expect the qrel file in correct format as the output of the pipeline. Please, try to implement this part by tomorrow night, for basic testing implementation you can take Roni's qrel prediction files, get query and document content and make the csv file as we have mentioned above.

_Note: I will be posting some implementation related doubts in some time as well, for you guys!_

### Let's finally end it, this weekend! All the best!

**Comment by ashishrana160796** [comment]
Final submission mail sent, closing this issue!
